### ISSUE TITLE
License

### ISSUE THREAD

**Issue by elhoim** [mdecrevoisier/SIGMA-detection-rules#17]
I really love this thorough backtested ruleset and I would like to use your rules qt $dayJob but the lack of license makes my management  worried and not wanting to implement until there is clarity.

Could you please decide for a license for the project(s)?

[Creative commons attribution](https://creativecommons.org/licenses/by/4.0/) might be a fitting choice

**Comment by mdecrevoisier** [comment]
Hi David, thank you for raising this topic. Generally speaking, SIGMA is a high level language outputing a logic that then need to be translated in the language of your detection solution (KQL, SPL, DSL, ...). As you will translate the original SIGMA query with your own logic and as the result will be different form the initial SIGMA concept, there is no need for your management to worry about that. 

However I will consider your request and may add this information in the next days.

**Comment by elhoim** [comment]
Their reasoning was that the translated query by pySigma would be seen as derivative work of the source (the sigma rule) but I am no copyright/licensing expert

**Comment by mdecrevoisier** [comment]
CC0 license added.
