### ISSUE TITLE
Help Understanding Correlations Between Event IDs

### ISSUE THREAD

**Issue by AlaZegnani** [mdecrevoisier/SIGMA-detection-rules#18]
Greetings,

I am having a little confusion when it comes to understanding how Event IDs are seperated in the IOCs content table in the Readme.md.

For example difference between  4728,4756,4732 AND 4728/4756. My initial thoughts are, when IDs are seperated with a comma "," that's an AND Operator (All IDs have to be present to detect the technique), whereas "/" means one of the Event IDs is enough for detection..

However I'm also seeing Event IDs seperated by "-" or some description values inbetween parantheses (), does this have any impact?. 

Your help in understanding main differences between these would be greatly appreciated.

Thankyou.

**Comment by mdecrevoisier** [comment]
Hi @AlaZegnani, thanks for the feedback. You are right, the definition of the separators is currently not clear and requires to check the SIGMA rule logic. I will see how I can improve this topic in a future release soon.

**Comment by mdecrevoisier** [comment]
Hi @AlaZegnani, thanks again for the feedback. I have updated the event ID information to clarify if it is about `OR` or `AND`operators.
