### ISSUE TITLE
microsoft defender blocking download of your repository

### ISSUE THREAD

**Issue by andreevianna** [mdecrevoisier/SIGMA-detection-rules#20]
Hi friends, during the download of this repo, my microsoft defender alarm and block the download, already test in two windows workstation with the same alert, now, i`m raise a ubuntu server to download and scan the files as well, but could be nice you verify this issue.

**Comment by mdecrevoisier** [comment]
Hi @andreevianna , this is not surprising based on the fact that several rules contains keywords related to encoded base64 powershell commands, Mimikatz, malicious commands... that could harm a system if they are not used properly.
