### ISSUE TITLE
Type in about column

### ISSUE THREAD

**Issue by AbelLykens** [mdecrevoisier/SIGMA-detection-rules#25]
> Set of SIGMA rules (>320) mapped to MITRE Att@k tactic and techniques 

should be

> Set of SIGMA rules (>320) mapped to MITRE Att&ck tactic and techniques 

Att@k --> Att&ck, or maybe even ATT&CK. 

Cheers.

**Comment by mdecrevoisier** [comment]
Thanks @AbelLykens , the description has been updated according to your advise.
